name: P0-Tutorial
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-20.04
    env:
      OS: ubuntu-20.04
      PYTHON: '3.6'
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@master
    
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.6

    - name: 'test tutorial'
      run: |
        cd tutorial
        python autograder.py | sed '/FAIL/w /tmp/output'
        echo score = $(echo 9-$(bash ../check_grade.sh) | bc) > /tmp/score # score

    - name: 'write score to comment'
      uses: mshick/add-pr-comment@v2
      with:
        message-path: /tmp/score
        repo-token: ${{ secrets.PAT }}

    - name: 'check error'
      run: bash check_error.sh
